CREATE DATABASE HW1;
USE HW1;
CREATE TABLE ACCOUNTS(
ID INTEGER PRIMARY KEY AUTO_INCREMENT,
EMAIL VARCHAR(255) NOT NULL UNIQUE,
USERNAME VARCHAR(255) NOT NULL UNIQUE,
PWD VARCHAR(255) NOT NULL
);
CREATE TABLE USER_TOKENS (
    ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    USERID INTEGER NOT NULL,
    TOKEN VARCHAR(255) NOT NULL UNIQUE,
    EXPIRES_AT DATETIME NOT NULL,
    FOREIGN KEY (USERID) REFERENCES ACCOUNTS(ID) ON DELETE CASCADE
);