CREATE DATABASE HW1;
USE HW1;

CREATE TABLE ACCOUNTS(
ID INTEGER PRIMARY KEY AUTO_INCREMENT,
EMAIL VARCHAR(255) NOT NULL UNIQUE,
USERNAME VARCHAR(255) NOT NULL UNIQUE,
PWD VARCHAR(255) NOT NULL,
AVATAR VARCHAR(255)
);

CREATE TABLE USER_TOKENS (
    ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    USERID INTEGER NOT NULL,
    TOKEN VARCHAR(255) NOT NULL UNIQUE,
    EXPIRES_AT DATETIME NOT NULL,
    INDEX IDX_USER (USERID),
    FOREIGN KEY (USERID) REFERENCES ACCOUNTS(ID) ON DELETE CASCADE
);

CREATE TABLE MOVIE_REVIEWS (
    ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    USERNAME VARCHAR(255) NOT NULL,
    INDEX IDX_USER (USERNAME),
    FOREIGN KEY (USERNAME) REFERENCES ACCOUNTS(USERNAME),
    FILM_ID VARCHAR(255) NOT NULL,
    FILM_NAME VARCHAR(255) NOT NULL,
    RECENSIONE VARCHAR(255) NOT NULL,
    VOTO DECIMAL(3,1),
    COVER MEDIUMTEXT,
    NUMLIKE INTEGER DEFAULT 0,
    UNIQUE(USERNAME,FILM_ID)
);

CREATE TABLE MOVIE_LIKES (
    ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    USERNAME VARCHAR(255) NOT NULL,
    INDEX IDX_USER (USERNAME),
    FOREIGN KEY (USERNAME) REFERENCES ACCOUNTS(USERNAME),
    FILM_ID VARCHAR(255) NOT NULL,
    FILM_NAME VARCHAR(255) NOT NULL,
    UNIQUE(USERNAME,FILM_ID),
    COVER MEDIUMTEXT
);

CREATE TABLE GAME_REVIEWS (
    ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    USERNAME VARCHAR(255) NOT NULL,
    INDEX IDX_USER (USERNAME),
    FOREIGN KEY (USERNAME) REFERENCES ACCOUNTS(USERNAME),
    GAME_ID INTEGER,
    GAME_NAME VARCHAR(255) NOT NULL,
    RECENSIONE VARCHAR(255) NOT NULL,
    VOTO DECIMAL(3,1),
    COVER MEDIUMTEXT,
    NUMLIKE INTEGER DEFAULT 0,
    UNIQUE(USERNAME,GAME_ID)
);

CREATE TABLE GAME_LIKES (
    ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    USERNAME VARCHAR(255) NOT NULL,
    INDEX IDX_USER (USERNAME),
    FOREIGN KEY (USERNAME) REFERENCES ACCOUNTS(USERNAME),
    GAME_ID INTEGER,
    GAME_NAME VARCHAR(255) NOT NULL,
    UNIQUE(USERNAME,GAME_ID),
    COVER MEDIUMTEXT
);

CREATE TABLE MOVIEREVIEW_LIKES (
    ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    REVIEW_ID INTEGER,
    USERNAME VARCHAR(255) NOT NULL,
    INDEX IDX_USER (USERNAME),
    INDEX IDX_REW (REVIEW_ID),
    FOREIGN KEY (REVIEW_ID) REFERENCES MOVIE_REVIEWS(ID),
    FOREIGN KEY (USERNAME) REFERENCES ACCOUNTS(USERNAME),
    UNIQUE(REVIEW_ID,USERNAME)
);

CREATE TABLE GAMEREVIEW_LIKES (
    ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    REVIEW_ID INTEGER,
    USERNAME VARCHAR(255) NOT NULL,
    INDEX IDX_USER (USERNAME),
    INDEX IDX_REW (REVIEW_ID),
    FOREIGN KEY (REVIEW_ID) REFERENCES GAME_REVIEWS(ID),
    FOREIGN KEY (USERNAME) REFERENCES ACCOUNTS(USERNAME),
    UNIQUE(REVIEW_ID,USERNAME)
);
