CREATE DATABASE HW1;
USE HW1;

CREATE TABLE ACCOUNTS(
ID INTEGER PRIMARY KEY AUTO_INCREMENT,
EMAIL VARCHAR(255) NOT NULL UNIQUE,
USERNAME VARCHAR(255) NOT NULL UNIQUE,
PWD VARCHAR(255) NOT NULL
);

CREATE TABLE USER_TOKENS (
    ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    USERID INTEGER NOT NULL,
    TOKEN VARCHAR(255) NOT NULL UNIQUE,
    EXPIRES_AT DATETIME NOT NULL,
    FOREIGN KEY (USERID) REFERENCES ACCOUNTS(ID) ON DELETE CASCADE
);

CREATE TABLE MOVIE_REVIEWS (
    ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    USER_ID INTEGER,
    FOREIGN KEY (USER_ID) REFERENCES ACCOUNTS(ID),
    FILM_ID VARCHAR(255) NOT NULL,
    FILM_NAME VARCHAR(255) NOT NULL,
    RECENSIONE VARCHAR(255) NOT NULL,
    VOTO INTEGER,
    COVER MEDIUMTEXT
);

CREATE TABLE MOVIE_LIKES (
    USERNAME VARCHAR(255) NOT NULL UNIQUE,
    FOREIGN KEY (USERNAME) REFERENCES ACCOUNTS(USERNAME),
    FILM_ID VARCHAR(255) NOT NULL,
    FILM_NAME VARCHAR(255) NOT NULL,
    PRIMARY KEY (USERNAME,FILM_ID),
    COVER MEDIUMTEXT
);

CREATE TABLE GAME_REVIEWS (
    ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    USER_ID INTEGER,
    FOREIGN KEY (USER_ID) REFERENCES ACCOUNTS(ID),
    GAME_ID INTEGER,
    GAME_NAME VARCHAR(255) NOT NULL,
    RECENSIONE VARCHAR(255) NOT NULL,
    VOTO INTEGER,
    COVER MEDIUMTEXT
);

CREATE TABLE GAME_LIKES (
    USERNAME VARCHAR(255) NOT NULL UNIQUE,
    FOREIGN KEY (USERNAME) REFERENCES ACCOUNTS(USERNAME),
    GAME_ID INTEGER,
    GAME_NAME VARCHAR(255) NOT NULL,
    PRIMARY KEY (USERNAME,GAME_ID),
    COVER MEDIUMTEXT
);